### ISSUE TITLE
Greengrass DeviceDefender: cannot deploy the latest version of the component

### ISSUE THREAD

**Issue by olivierpichon** [aws-greengrass/aws-greengrass-device-defender#15]
**Describe the bug**
The documentation of this component available here: https://docs.aws.amazon.com/greengrass/v2/developerguide/device-defender-component.html states that the latest version of the component is 3.1.3, (3.1.3 being the version compatible with Nucleus 2.9.0). But trying to use this version and issuing a new deployment gives the following error:
```
FAILED_NO_STATE_CHANGE: NoAvailableComponentVersionException: No local or cloud component version satisfies the requirements Component aws.greengrass.DeviceDefender 3.1.3
```

**To Reproduce**
Try to deploy DeviceDefender 3.1.3

**Expected behavior**
No error

**Actual behavior**
Deployment error

**Environment**
 - OS: Ubuntu
 - Nucleus version: 2.9.6

**Additional context**
Looks like the latest tags from this repo are also not inline with the documentation. Not sure what to do and which version to use when having Nucleus 2.9.x then...

**Comment by MikeDombo** [comment]
Hello, please use version 3.1.1. 3.1.2 and 3.1.3 do not exist and the documentation will be updated.

You can always view the proper versions in the AWS Console under Greengrass Devices -> Components -> Public Components.
